$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "Language Reader - Android SDK 自动修复" -ForegroundColor Cyan
Write-Host "-----------------------------------"

$projectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$localProps = Join-Path $projectDir "local.properties"

$candidates = New-Object System.Collections.Generic.List[string]

function Add-Candidate([string]$p) {
    if ([string]::IsNullOrWhiteSpace($p)) { return }
    $expanded = [Environment]::ExpandEnvironmentVariables($p.Trim())
    if (-not $candidates.Contains($expanded)) { $candidates.Add($expanded) }
}

# 1) Environment variables
Add-Candidate $env:ANDROID_SDK_ROOT
Add-Candidate $env:ANDROID_HOME

# 2) Default Windows SDK locations
Add-Candidate "$env:LOCALAPPDATA\Android\Sdk"
Add-Candidate "$env:USERPROFILE\AppData\Local\Android\Sdk"

# 3) Common D-drive locations (user prefers D:)
Add-Candidate "D:\Android\Sdk"
Add-Candidate "D:\AndroidSDK"
Add-Candidate "D:\Android\AndroidSdk"
Add-Candidate "D:\Sdk"
Add-Candidate "D:\SDK"
Add-Candidate "D:\studio android\Sdk"
Add-Candidate "D:\studio android\sdk"

# 4) Existing local.properties if it contains a usable path
if (Test-Path $localProps) {
    Get-Content $localProps | ForEach-Object {
        if ($_ -match '^\s*sdk\.dir\s*=\s*(.+)\s*$') {
            $raw = $Matches[1] -replace '\\\\','\'
            Add-Candidate $raw
        }
    }
}

function Is-AndroidSdk([string]$p) {
    if (-not (Test-Path $p -PathType Container)) { return $false }
    $platforms = Join-Path $p "platforms"
    $platformTools = Join-Path $p "platform-tools"
    return (Test-Path $platforms -PathType Container) -and (Test-Path $platformTools -PathType Container)
}

$sdk = $null
foreach ($candidate in $candidates) {
    if (Is-AndroidSdk $candidate) {
        $sdk = (Resolve-Path $candidate).Path
        break
    }
}

# 5) Last-resort search on D: for likely SDK directories, kept deliberately shallow.
if (-not $sdk -and (Test-Path "D:\")) {
    Write-Host "常见路径没有找到，正在 D: 盘快速查找 Android SDK..." -ForegroundColor Yellow
    $roots = @(
        "D:\Android",
        "D:\studio android",
        "D:\Program Files",
        "D:\Programs",
        "D:\Dev",
        "D:\Development"
    )
    foreach ($r in $roots) {
        if (-not (Test-Path $r)) { continue }
        Get-ChildItem -Path $r -Directory -Recurse -Depth 3 -ErrorAction SilentlyContinue | ForEach-Object {
            if (-not $sdk -and (Is-AndroidSdk $_.FullName)) {
                $sdk = $_.FullName
            }
        }
        if ($sdk) { break }
    }
}

if (-not $sdk) {
    Write-Host ""
    Write-Host "没有自动找到 Android SDK。" -ForegroundColor Red
    Write-Host "请在 Android Studio 打开：Tools > SDK Manager" -ForegroundColor Yellow
    Write-Host "把顶部 'Android SDK Location' 的路径复制给 ChatGPT，我会直接给你写好。" -ForegroundColor Yellow
    Write-Host ""
    Read-Host "按 Enter 退出"
    exit 1
}

# local.properties uses escaped backslashes or forward slashes; forward slashes are safest.
$sdkForGradle = $sdk -replace '\\','/'
$content = @"
# Auto-generated by Language Reader SDK setup
sdk.dir=$sdkForGradle
"@

Set-Content -Path $localProps -Value $content -Encoding ASCII

Write-Host ""
Write-Host "已找到 Android SDK：" -ForegroundColor Green
Write-Host "  $sdk" -ForegroundColor White
Write-Host ""
Write-Host "已写入：" -ForegroundColor Green
Write-Host "  $localProps" -ForegroundColor White
Write-Host ""
Write-Host "现在回到 Android Studio：" -ForegroundColor Cyan
Write-Host "  File > Sync Project with Gradle Files" -ForegroundColor Cyan
Write-Host ""
Read-Host "按 Enter 关闭窗口"
